apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/job: appkube-cmdb_test
    prometheus.io/path: /management/prometheus
    prometheus.io/port: '6057'
    prometheus.io/label: environment=devtest,app=appkube_cmdb_test
  name: {{ include "appkube-cmdb-service.fullname" . }}
  labels:
    {{- include "appkube-cmdb-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appkube-cmdb-service.selectorLabels" . | nindent 4 }}
